### PR TITLE
support RTSP by using `ffmpeg` to convert the stream

### LINKED ISSUE #12: Add rtsp source support for realtime analysis
Realtime analysis should support RTSP streams as source for audio data

example

`birdnet realtime --rtsp rtsp://user@pass@url`

### PR DESCRIPTION
**Pull request by twt--**
adding very basic support for RTSP.

usage: `birdnet-go realtime --rtsp rtsp://...`
if an rtsp URL is not provided, it will default to using the audio device.

I've been running this for the past week without issues.

resolves #12

### CODE REVIEW

**Comment by tphakala** [comment]
Thank you, much appreciated!

**Comment by enjikaka** [comment]
Is multiple RTSP streams supported?

**Comment by tphakala** [comment]
No, not yet.

**Comment by tphakala** [comment]
But I think there is a workaround, I have not tested this but I don't think that anything prevents you from running multiple instances of birdnet-go which each point to same SQLite file. Enable Web UI for only one of processes and you should see detections from each stream in single view.

**Pull request merged**
