### PR TITLE
Add initial Dockerfile setup

### PR DESCRIPTION
**Pull request by isZumpo**
Hi, I am really happy to see this project coming along nicely! One issue I always had with the original BirdNET-Pi project was that is did not support docker. Which made it really hard to try out before deciding to run it on a raspberry, since it pretty much required a dedicated VM...

While the go approach for this project makes it way easier to try out, I still believe a docker image could be beneficial! Therefore, I would like to make a contribution on getting us started with a initial dockerfile.

This PR allows for BirdNET-Go to be built and bundled into a container. The container will by default execute
the realtime command, starting the server. The image is currently based on debian bookworm since I found that easiest to get running. However, in the future it might be better bundle it in a alpine image to reduce the size even more. It might also be of interest to utilize Github Actions to build a docker for every release. Would happily contribute to that in the future too!

### CODE REVIEW

**Comment by tphakala** [comment]
Thank you! Contributions are much appreciated

**Comment by isZumpo** [comment]
Wow that was quick! One issue I experienced that you might be aware of how to fix is that if I don't copy in the .git folder while building the project in docker, then it will try to grab birdnet-go stuff from github rather than locally. I am not that experienced with go... Do you know if there is some way to work around that?

**Comment by tphakala** [comment]
I guess it is fetching go dependencies, like GORM, SQLite driver etc. modules, but I am not sure. I need to test this and see what it does.

**Comment by isZumpo** [comment]
Just double checked. Appears to not be the case anymore, probably some unrelated issue I had while constructing the dockerfile. Removing .git works fine now!

**Pull request merged**
