### PR TITLE
Add basic github action for building docker image

### PR DESCRIPTION
**Pull request by isZumpo**
Implements a basic github action job that will for every commit to the main branch, build and push a docker
image to the latest tag. The latest tag will get overwritten after each commit.

In the future it might be better to instead decide on some better tagging strategy.

### CODE REVIEW

**Comment by isZumpo** [comment]
@tphakala there appears to be some sort of permission error now when the action runs:

**denied: installation not allowed to Create organization package**

I did not experience this when running it in my fork. Perhaps there is a setting that must be adjusted for the repository?

**Comment by tphakala** [comment]
It was a privilege issue, now fixed.

**Comment by isZumpo** [comment]
> It was a privilege issue, now fixed.

Great! Now it seems to be running as expected. Could you also make the docker packages public? Then it should be accessible for everyone.

**Comment by tphakala** [comment]
done!

**Comment by tphakala** [comment]
I updated workflow to support multiplatform builds, at the moment it builds linux/amd64 and linux/arm64

**Pull request merged**
